@startuml use-case

skinparam actorStyle awesome
:Chef d'agence:
:Guichetier:
rectangle Système {
    (Rendre inactif un client)
    (Gérer les employés)
    (Débiter un compte)
    (Consulter un compte)
    (Créer un nouveau client)
    (Modifier infos client)
    (Créditer compte)
    (Virment de compte à compte)
    (Cloturer un compte)
    (Créer un compte)

    (Générer un relevé mensuel d’un compte en PDF)
    (Gérer, ou faire le « CRUD » des prélèvements automatiques)
    (Effectuer un Débit exceptionnel)
    (Simuler un emprunt)
    (Simuler une assurance d’emprunt)

    (fonctionnalité supplémentaire 1)
    (fonctionnalité supplémentaire 2)
    (Générer les relevés mensuels en PDF)
    (Exécuter les prélèvements automatiques)
}


(Guichetier) <|-right- (Chef d'agence)

left to right direction
:Chef d'agence: --> (Rendre inactif un client)
:Chef d'agence: --> (Gérer les employés)
:Chef d'agence: --> (Effectuer un Débit exceptionnel)
:Chef d'agence: --> (Simuler un emprunt)
:Chef d'agence: --> (Simuler une assurance d’emprunt)

:Chef d'agence: --> (Générer les relevés mensuels en PDF)
:Chef d'agence: --> (Exécuter les prélèvements automatiques)


(Guichetier) --> (Débiter un compte) 
(Guichetier) --> (Consulter un compte) 
(Guichetier) --> (Créer un nouveau client) 
(Guichetier) --> (Modifier infos client) 
(Guichetier) --> (Créditer compte) 
(Guichetier) --> (Virment de compte à compte) 
(Guichetier) --> (Cloturer un compte) 
(Guichetier) --> (Créer un compte)

(Guichetier) --> (Générer un relevé mensuel d’un compte en PDF)
(Guichetier) --> (Gérer, ou faire le « CRUD » des prélèvements automatiques)


@enduml