@startuml
ClientsManagementController -> ClientsManagement : doComptesClient()  
    ClientsManagement -> ComptesManagement : gererComptesClient()
        ComptesManagement -> ComptesManagementController : doComptesManagementDialog()
            ComptesManagementController -> Stage : displayDialog()
                Stage -> Stage : showAndWait()
            Stage --> ComptesManagementController
        ComptesManagementController --> ComptesManagement
    ComptesManagement --> ClientsManagement
ClientsManagement --> ClientsManagementController
    
@enduml