@startuml
ClientsManagementController -> ClientsManagement : doModifierClient()
    ClientsManagement -> AccessClient : modifierClient()
        AccessClient -> AccessClient : updateClient()
    AccessClient --> ClientsManagement
ClientsManagement --> ClientsManagementController
@enduml