name: umltopng
on: [push]
jobs:
  create:
    runs-on: ubuntu-lastest
    steps:
    - name: checkout
      uses: actions/checkout@v1 # récuprer le depo courant
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5 # permer de générer le svg
      with:
        path: plantuml
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
